api:
  version: 1.0.0
  title: Proyecto Logistica
  basePackage: com.example.logistica
  description: Automated JSON API documentation for API's built with Spring
  terms: https://
server:
  servlet:
    context-path: /logistica-service
  port : 8080
# ===============================
# = DATA SOURCE MYSQL
# ===============================

#configuracion mysql basica

spring:
  datasource:
    #url: jdbc:postgresql://10.19.34.188/zee_db
    url: jdbc:mysql://localhost:3306/logistica?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        # Hibernate ddl auto  (create, create-drop, validate, update, none)
        ddl-auto: none

    # swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs
