api:
  version: 1.0.0
  title: Proyecto Logistica
  basePackage: com.example.logistica
  description: Automated JSON API documentation for API's built with Spring
  terms: https://
# ===============================
# = DATA SOURCE MYSQL
# ===============================

#configuracion mysql basica

spring:
  datasource:
    url: jdbc:mysql://u8dqcprei4mt3vlb:h7tOheQEuqGGAFURWbGH@bexuqazczajpyzggicwv-mysql.services.clever-cloud.com:3306/bexuqazczajpyzggicwv
    username: u8dqcprei4mt3vlb
    password: h7tOheQEuqGGAFURWbGH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

    # swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs
